SET CURRENT_DB = CURRENT_DATABASE();
SET CURRENT_SCHEMA = CURRENT_SCHEMA();

CREATE OR REPLACE TABLE USER (
    ID              STRING          NOT NULL DEFAULT UUID_STRING(),
    EMAIL           STRING          NOT NULL,
    FIRST_NAME      STRING,
    LAST_NAME       STRING,
    PASSWORD_HASH   STRING,
    ROLE            STRING          DEFAULT 'user',
    IS_ACTIVE       BOOLEAN         DEFAULT TRUE,
    CREATED_AT      TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE USER ADD CONSTRAINT USER_EMAIL_UNIQUE UNIQUE (EMAIL);
